name: Polars Pipeline CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Set up Rye
              uses: eifinger/setup-rye@v3
              with:
                version: "latest"

            - name: Lint
              run: rye lint

            - name: Test
              run: rye test
